/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. \u203C\uFE0F DO NOT MODIFY THIS FILE \u203C\uFE0F
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//important': RouteRecordInfo<'//important', '/important', Record<never, never>, Record<never, never>>,
    '//nested/first': RouteRecordInfo<'//nested/first', '/nested/first', Record<never, never>, Record<never, never>>,
    '//nested/first/second': RouteRecordInfo<'//nested/first/second', '/nested/first/second', Record<never, never>, Record<never, never>>,
    '//nested/first/second/third': RouteRecordInfo<'//nested/first/second/third', '/nested/first/second/third', Record<never, never>, Record<never, never>>,
    '//settings': RouteRecordInfo<'//settings', '/settings', Record<never, never>, Record<never, never>>,
    '//simple': RouteRecordInfo<'//simple', '/simple', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
  }
}
